id: A7DFEB7F9
title: The Last Testament of Katok Dampa Deshek
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:20:31.051552
  last_modified_at: 2022-03-01 06:20:31.051556
