id: A7DFEB7F9
title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin Nyima
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:20:31.049448
  last_modified_at: 2022-03-01 06:20:31.049451
