id: A7DFEB7F9
title: The Testament Prayer to Orgyen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:20:31.054769
  last_modified_at: 2022-03-01 06:20:31.054776
