id: A7DFEB7F9
title: Words Spoken at the Moment of Passing
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:20:31.056435
  last_modified_at: 2022-03-01 06:20:31.056439
